name = "LeanCopilotTest"
version = "0.1.0"
defaultTargets = []

moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]

[[require]]
name = "LeanCopilot"
git = "https://github.com/lean-dojo/LeanCopilot.git"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
