name = "LeanCopilotTest"
version = "0.1.0"
defaultTargets = ["leancopilottest"]

moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]

[[lean_lib]]
name = "LeanCopilotTest"
nativeFacets = ["shared"]

[[lean_exe]]
name = "leancopilottest"
root = "Main"

[[require]]
name = "LeanCopilot"
git = "https://github.com/lean-dojo/LeanCopilot.git"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "CoW"