#!/usr/bin/env python3

from pathlib import Path
import csv
import re


# ============================================================
# PATH CONFIGURATION
# ============================================================

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent

# Project structure:
#
# Formal_Proof_Generation_Project/
# ├── examples/
# │   ├── List/
# │   ├── Nat/
# │   ├── Prop/
# │   └── Group/
# └── scripts/
#     └── analyze_examples_tactic_difficulty.py

EXAMPLES_DIR = PROJECT_DIR / "examples"

# Output:
# Formal_Proof_Generation_Project/
# └── scripts/
#     └── difficulty_analysis_summary/
#
# The CSV generated by this script will be:
# examples_tactic_analysis.csv

DIFFICULTY_ANALYSIS_DIR = (
    SCRIPT_DIR / "difficulty_analysis_summary"
)


# ============================================================
# DIFFICULTY CLASSIFICATION
# ============================================================

def get_difficulty(tactic_count):
    """
    Difficulty classification based on tactic count.

    1-3  -> easy
    4-6  -> medium
    >6   -> hard
    """

    if tactic_count <= 3:
        return "easy"
    elif tactic_count <= 6:
        return "medium"
    else:
        return "hard"


# ============================================================
# TACTIC KEYWORDS
# ============================================================

TACTIC_KEYWORDS = {
    "apply",
    "by_cases",
    "by_contra",
    "cases",
    "constructor",
    "contradiction",
    "exact",
    "funext",
    "have",
    "induction",
    "intro",
    "left",
    "obtain",
    "rcases",
    "repeat",
    "rfl",
    "rintro",
    "rw",
    "simp",
    "simpa",
    "simp_all",
    "split",
    "split_ifs",
    "subst",
    "unfold",
    "contrapose",
    "contrapose!",
    "lia",
}


# ============================================================
# REMOVE COMMENTS AND STRING LITERALS
# ============================================================

def remove_comments_and_strings(text):
    """
    Remove Lean comments and string literals.

    Handles:
        -- single-line comments
        /- block comments -/
        nested block comments
        "string literals"

    Newlines are preserved where possible.
    """

    result = []

    i = 0
    n = len(text)

    in_line_comment = False
    block_comment_depth = 0
    in_string = False

    while i < n:

        # ----------------------------------------------------
        # Inside single-line comment
        # ----------------------------------------------------

        if in_line_comment:

            if text[i] == "\n":
                in_line_comment = False
                result.append("\n")

            i += 1
            continue

        # ----------------------------------------------------
        # Inside block comment
        # ----------------------------------------------------

        if block_comment_depth > 0:

            if text.startswith("/-", i):
                block_comment_depth += 1
                i += 2
                continue

            if text.startswith("-/", i):
                block_comment_depth -= 1
                i += 2
                continue

            if text[i] == "\n":
                result.append("\n")

            i += 1
            continue

        # ----------------------------------------------------
        # Inside string
        # ----------------------------------------------------

        if in_string:

            if text[i] == "\\":
                i += 2
                continue

            if text[i] == '"':
                in_string = False

            i += 1
            continue

        # ----------------------------------------------------
        # Start single-line comment
        # ----------------------------------------------------

        if text.startswith("--", i):
            in_line_comment = True
            i += 2
            continue

        # ----------------------------------------------------
        # Start block comment
        # ----------------------------------------------------

        if text.startswith("/-", i):
            block_comment_depth = 1
            i += 2
            continue

        # ----------------------------------------------------
        # Start string
        # ----------------------------------------------------

        if text[i] == '"':
            in_string = True
            i += 1
            continue

        # ----------------------------------------------------
        # Normal character
        # ----------------------------------------------------

        result.append(text[i])
        i += 1

    return "".join(result)


# ============================================================
# EXTRACT THEOREMS AND PROOF BODIES
# ============================================================

def extract_theorem_proofs(text):
    """
    Extract theorem names and proof bodies.

    Expected form:

        theorem theorem_name ... := by
            ...
    """

    clean_text = remove_comments_and_strings(text)

    theorem_pattern = re.compile(
        r"(?m)^\s*theorem\s+([A-Za-z0-9_!?']+)"
    )

    matches = list(theorem_pattern.finditer(clean_text))

    theorems = []

    for index, match in enumerate(matches):

        theorem_name = match.group(1)
        theorem_start = match.start()

        if index + 1 < len(matches):
            theorem_end = matches[index + 1].start()
        else:
            theorem_end = len(clean_text)

        theorem_text = clean_text[
            theorem_start:theorem_end
        ]

        # ----------------------------------------------------
        # Find := by
        # ----------------------------------------------------

        proof_match = re.search(
            r":=\s*by\b",
            theorem_text
        )

        if proof_match is None:
            continue

        proof_start = proof_match.end()

        proof_body = theorem_text[
            proof_start:
        ]

        theorems.append({
            "name": theorem_name,
            "proof": proof_body,
        })

    return theorems


# ============================================================
# COUNT TACTICS
# ============================================================

def find_tactics(proof):
    """
    Find occurrences of the verified tactic keywords.

    Tactic arguments are not counted separately.

    Example:

        simp [List.length_append]

    counts as:

        simp = 1

    Example:

        intro h <;> simp

    counts as:

        intro = 1
        simp  = 1

    Total = 2
    """

    sorted_tactics = sorted(
        TACTIC_KEYWORDS,
        key=len,
        reverse=True
    )

    pattern = re.compile(
        r"(?<![A-Za-z0-9_'])("
        + "|".join(
            re.escape(tactic)
            for tactic in sorted_tactics
        )
        + r")(?![A-Za-z0-9_'])"
    )

    return pattern.findall(proof)


def count_tactics(proof):
    """
    Return the tactic count and individual tactics.
    """

    tactic_names = find_tactics(proof)

    return len(tactic_names), tactic_names


# ============================================================
# ANALYZE ONE LEAN FILE
# ============================================================

def analyze_source_file(source_file, domain):
    """
    Analyze all theorem proofs in one Lean source file.
    """

    if not source_file.exists():
        raise FileNotFoundError(
            f"Source file not found:\n{source_file}"
        )

    text = source_file.read_text(
        encoding="utf-8"
    )

    theorem_proofs = extract_theorem_proofs(text)

    results = []

    for theorem in theorem_proofs:

        tactic_count, tactic_names = (
            count_tactics(
                theorem["proof"]
            )
        )

        difficulty = get_difficulty(
            tactic_count
        )

        results.append({
            "theorem_name":
                theorem["name"],

            "file_name":
                source_file.name,

            "domain":
                domain,

            "tactic_count":
                tactic_count,

            "difficulty":
                difficulty,

            "tactics":
                ", ".join(tactic_names),
        })

    return results


# ============================================================
# FIND EXAMPLE LEAN FILES
# ============================================================

def find_example_files():
    """
    Find all .lean files inside the four example domains.

    The folders can contain one or multiple Lean files.
    """

    if not EXAMPLES_DIR.exists():
        raise FileNotFoundError(
            f"Examples directory not found:\n{EXAMPLES_DIR}"
        )

    domain_dirs = {
        "list": EXAMPLES_DIR / "List",
        "nat": EXAMPLES_DIR / "Nat",
        "prop": EXAMPLES_DIR / "Prop",
        "group": EXAMPLES_DIR / "Group",
    }

    source_files = []

    for domain, domain_dir in domain_dirs.items():

        if not domain_dir.exists():
            print(
                f"WARNING: Domain directory not found: "
                f"{domain_dir}"
            )
            continue

        for source_file in sorted(
            domain_dir.rglob("*.lean")
        ):
            source_files.append(
                (domain, source_file)
            )

    return source_files


# ============================================================
# WRITE CSV
# ============================================================

def write_summary_csv(results):
    """
    Write theorem-wise tactic analysis to CSV.
    """

    DIFFICULTY_ANALYSIS_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    output_file = (
        DIFFICULTY_ANALYSIS_DIR
        / "examples_tactic_analysis.csv"
    )

    fieldnames = [
        "ID",
        "theorem_name",
        "file_name",
        "domain",
        "tactic_count",
        "difficulty",
        "tactics",
    ]

    with open(
        output_file,
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        for index, result in enumerate(
            results,
            start=1
        ):

            writer.writerow({
                "ID":
                    index,

                "theorem_name":
                    result["theorem_name"],

                "file_name":
                    result["file_name"],

                "domain":
                    result["domain"],

                "tactic_count":
                    result["tactic_count"],

                "difficulty":
                    result["difficulty"],

                "tactics":
                    result["tactics"],
            })

    return output_file


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 100)
    print(
        "EXAMPLES TACTIC COUNT AND DIFFICULTY ANALYSIS"
    )
    print("=" * 100)

    print(
        f"Project directory : {PROJECT_DIR}"
    )

    print(
        f"Examples directory: {EXAMPLES_DIR}"
    )

    print(
        f"Output directory  : {DIFFICULTY_ANALYSIS_DIR}"
    )

    print()

    source_files = find_example_files()

    if not source_files:
        raise RuntimeError(
            f"No .lean files found inside:\n"
            f"{EXAMPLES_DIR}"
        )

    all_results = []

    domain_order = {
        "list": 0,
        "nat": 1,
        "prop": 2,
        "group": 3,
    }

    # --------------------------------------------------------
    # Analyze every Lean file
    # --------------------------------------------------------

    for domain, source_file in source_files:

        print(
            f"Analyzing {domain}: "
            f"{source_file}"
        )

        results = analyze_source_file(
            source_file,
            domain,
        )

        print(
            f"  Found {len(results)} theorem proofs."
        )

        all_results.extend(results)

    # --------------------------------------------------------
    # Sort results by domain and theorem name
    # --------------------------------------------------------

    all_results.sort(
        key=lambda result: (
            domain_order.get(
                result["domain"],
                99
            ),
            result["theorem_name"].lower(),
        )
    )

    # --------------------------------------------------------
    # Write CSV
    # --------------------------------------------------------

    detailed_csv = write_summary_csv(
        all_results
    )

    # --------------------------------------------------------
    # Final summary
    # --------------------------------------------------------

    print()
    print("=" * 100)
    print("ANALYSIS COMPLETE")
    print("=" * 100)

    print(
        f"Total theorem proofs analyzed : "
        f"{len(all_results)}"
    )

    print(
        f"Detailed results               : "
        f"{detailed_csv}"
    )

    print("=" * 100)


if __name__ == "__main__":
    main()
